### ISSUE TITLE
Is it possible to load the config file from an external server?

### ISSUE THREAD

**Issue by willvlad** [Ephenodrom/Flutter-Global-Config#1]
I see you have the ability to do so locally, but I wondered if it's possible to load something from an external server?

**Comment by Ephenodrom** [comment]
Yes, this is possible, but the configuration must be loaded from the server at APP Start. Currently this step has to be done manually. But I will extend the class GlobalConfiguration with such a function.

**Comment by Ephenodrom** [comment]
I added the new method loadFromUrl(); The method loads a json from a URL with the given PARAMETERS and HEADERS. I added an example in the README.md file.

To use it, update to version 0.1.3.

**Comment by willvlad** [comment]
Great, thanks for the prompt reaction! What's the current behaviour of the app, if the loading takes a few secs? Does it just hang? Since we wrap the main run MyApp, I suppose we can't show a splash screen while waiting?
