### ISSUE TITLE
Cannot Update Null Value

### ISSUE THREAD

**Issue by young-altair** [Ephenodrom/Flutter-Global-Config#10]
Thank you for this great package. I have problems when I want to update the value that originally Null became one of the string / int values.
The Error Log
```
E/flutter ( 9084): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: wrong type
E/flutter ( 9084): #0      GlobalConfiguration.updateValue (package:global_configuration/global_configuration.dart:138:13)
E/flutter ( 9084): #1      _MapScreenState._sendAttendance (package:n4_attendance/app/screens/map_screen.dart:519:17)
E/flutter ( 9084): <asynchronous suspension>
....```

**Comment by Ephenodrom** [comment]
@young-altair 
Hello and thanks for using this package. Normally there should be no "NULL" when loading a configuration. But nethertheless, a made a small change with version 1.5.0. It's now possible to update null values.

Please refer to the latest version in your pubspec.yaml file.

Regards
