### ISSUE TITLE
Updating configuration file on update?

### ISSUE THREAD

**Issue by saidlp** [Ephenodrom/Flutter-Global-Config#11]
Hi and thank you for a handy little lib!
no bug report here, but a suggestion: maybe I missed something, but it seems that at the moment, when updating an option, only the option map is updated and not the source configuration file.
It could be very convenient to have an option to have the config file updated too, so that when starting up the app again, the updated configuration would be taken into account.

Best regards

**Comment by Ephenodrom** [comment]
Hello @saidlp 

The global config package is not persistent. You once load the configuration on app start from a source and the only purpose of the package is to give access to it everywhere inside your flutter app.

If you want to update data and it has to be persistent check out my EZ Flutter Framework at https://github.com/Ephenodrom/EZ-Flutter. The EZ Flutter framework uses the global config package to store data persistent. Check out the documentation at https://ez-flutter.de/docs/application_settings. That's the reason where is an update method in the GlobalConfiguration class.

If you don't want to use the framework, take a look at https://github.com/Ephenodrom/EZ-Flutter/blob/master/lib/src/model/EzSettings.dart and create your own implementation.

I hope that makes it clear :).

Regards and thanks for opening an issue!

**Comment by saidlp** [comment]
Thank you for your fast reply @Ephenodrom .
I'll make my own implementation for the persistence part, but you lib was a nice source of inspiration :)
Thanks again!

**Comment by Ephenodrom** [comment]
@saidlp Glad I could help:).
