### ISSUE TITLE
Use different configurations based on current build mode

### ISSUE THREAD

**Issue by hunorbatori** [Ephenodrom/Flutter-Global-Config#14]
Is there any built in way to load different configs based on what is the current build mode?

I mean under the `cfg` folder there could be an `app_settings.json` for the general things, `app_settings.debug.json` for debug values like local server urls, and `app_settings.release.json` for release values.

**Comment by Ephenodrom** [comment]
Hello @hunorbatori 

Currently I don't know any way to achieve this easily. The current way to achieve this is to create a seperate main file for each "stage" you want to deploy.

If you have the following stages : dev / production

You would create the following main files : main_dev.dart / main_production.dart

Then you can choose how to run your app via : 
```
flutter run -t lib/main_debug.dart
```
It is also possible to build the app using different main files. You have to look up for the corresponding command.

Take a look at :

https://stackoverflow.com/questions/47438564/how-do-i-build-different-versions-of-my-flutter-app-for-qa-dev-prod/53496597#53496597

Important note : This answer is from 2019, maybe there is a chance that there is a easier way. You need to somehow access the build environment in your main file then you can do some easy if-else to load the corresponding config file.

**Comment by Ephenodrom** [comment]
And you should also take a look at this answer: 

https://github.com/flutter/flutter/issues/11392#issuecomment-461668769

**Comment by hunorbatori** [comment]
Thank you for all your answers!
