### ISSUE TITLE
Read nested values in a json

### ISSUE THREAD

**Issue by SaulRinconOlvera** [Ephenodrom/Flutter-Global-Config#16]
Hello, 

I'm, try to read nested values in a json string and I don't know how to do that because I'm new in Dart/Flutter. 
In an ordinary json string like next:
`
{  
    "configuration": {
        "key1": "value1",
        "key2": "value2"
    }
}`

I want to read the "key1" value. In C# we can do something lik: ` string value = jsonConfig.ReadValue["configuration:key1"];`
I add a similar function in the Flutter-Global-Config thah it permit read a nested value using the metho` getDeepValue<T>` whet "T" is the data type that you are waiting read.

You can use something like: `GlobalConfiguration().getDeepValue<Color>("appColors:primaryColor");`. I this case the value readed is a string  with a hexadecimal RGB value, for this cases I'm added a function to convert the striing to a Color object.

Here some examples:

```
String stringValue = GlobalConfiguration().getDeepValue<String>("myStringValue");
String stringValue = GlobalConfiguration().getDeepValue<String>("values:myNestedStringValue");
int intValue =  GlobalConfiguration().getDeepValue<int>("myIntValue");
int intValue =  GlobalConfiguration().getDeepValue<int>("values:myNestedIntValue");
bool boolValue = GlobalConfiguration().getDeepValue<bool>("myBoleanValue");

```

**Comment by Ephenodrom** [comment]
Hello and sorry for the late response!
This is already covered by the package. If you want to access nested values you can do it like this : 

```dart
GlobalConfiguration().get("configuration")['key1'];
```

But the PR adds some nice features, so i merged the pull request and release the version 1.6.0 on pub.dev.

Regards
