### ISSUE TITLE
cant add await GlobalConfiguration().loadFromUrl(           ""); to splash screean

### ISSUE THREAD

**Issue by TSCSOftware** [Ephenodrom/Flutter-Global-Config#18]
import 'package:firebase_remote_config/firebase_remote_config.dart';
import 'package:flutter/material.dart';
import 'package:global_configuration/global_configuration.dart';

import 'package:readhubnew/logic/callAPI.dart';
import 'package:readhubnew/logic/config.dart';
import 'package:readhubnew/main.dart';
import 'package:connectivity/connectivity.dart';
import 'package:readhubnew/Components/components.dart';

class Splash extends StatefulWidget {

  @override
  _SplashState createState() => _SplashState();
}

class _SplashState extends State<Splash> {
  String mywebadse =
      "https://public-api.wordpress.com/wp/v2/sites/kiyawamulk.wordpress.com/posts?per_page=5&_embed";

  Future<bool> check() async {

    var connectivityResult = await (Connectivity().checkConnectivity());

    if (connectivityResult == ConnectivityResult.mobile) {
      await GlobalConfiguration().loadFromUrl(
          "https://raw.githubusercontent.com/TSCSOftware/api/master/api1.json");

      return true;
    } else if (connectivityResult == ConnectivityResult.wifi) {
      return true;
    }
    return false;

  }
  Future<void> getconfig() async {

      await GlobalConfiguration().loadFromUrl(
          "https://myconfig url.com/api1.json");

  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    sendEnglishPosts(mywebadse).then((onValue) {
      {
        Navigator.pushAndRemoveUntil(
          context,
          MaterialPageRoute(builder: (context) => MyHomePage()),
          (Route<dynamic> route) => false,
        );
      }
      ;
    }).catchError((onError) {
      showColoredToast('Please Check Your Internet Connection & Try again!');
    });
    initMobileNumberState(){};
  }

  @override
  Widget build(BuildContext context) {

    double height = MediaQuery.of(context).size.height;
    return Scaffold(
        body: Container(
      decoration: new BoxDecoration(
        image: new DecorationImage(
          colorFilter: new ColorFilter.mode(
              Colors.white.withOpacity(0.45), BlendMode.dstATop),
          image: new AssetImage("assets/images/back.png"),
          fit: BoxFit.fill,
        ),
      ),
      child: new Center(
          child: Column(
        children: <Widget>[
          Expanded(
              child: Container(
            child: Image.asset('assets/images/logo.png'),
            height: height / 3,
            width: height / 3,
          )),
          Container(child: CircularProgressIndicator()),
          Container(
            margin: EdgeInsets.all(8),
            padding: const EdgeInsets.all(8.0),
            child: Text(
              "welcome",
              style: TextStyle(
                  letterSpacing: 3,
                  color: Colors.red,
                  fontSize: 20.0,
                  fontWeight: FontWeight.bold,
                  fontFamily: 'Poppins'),
            ),
          ),
        ],
      )),
    ));
  }
}

**Comment by Ephenodrom** [comment]
No question in this issue and the code is not quite readable.
