### ISSUE TITLE
http ^0.13.0 Library upgrade required

### ISSUE THREAD

**Issue by fitwin** [Ephenodrom/Flutter-Global-Config#22]
Hello, 

I upgraded my flutter version to 2.0.0 and I upgraded my firebase libraries. There has been an upgrade on FirebaseStorage, and then this library is blocking me of upgrading my project to use the latest version of firebase.

Because firebase_storage >=8.0.0 depends on firebase_storage_web ^1.0.0 which depends on http ^0.13.0, firebase_storage >=8.0.0 requires http ^0.13.0.
And because global_configuration >=1.6.0 depends on http ^0.12.2, firebase_storage >=8.0.0 is incompatible with global_configuration >=1.6.0.
So, because fitwin depends on both global_configuration ^1.6.0 and firebase_storage ^8.0.0, version solving failed.
pub get failed (1; So, because fitwin depends on both global_configuration ^1.6.0 and firebase_storage ^8.0.0, version solving failed.)

**Comment by Ephenodrom** [comment]
The PR is merged, I will upload version 2.0.0-nullsafety.0 to pub.dev today.
