### ISSUE TITLE
doesn't support the latest http version 0.13.

### ISSUE THREAD

**Issue by rahat1994** [Ephenodrom/Flutter-Global-Config#24]
I have a big project and I have recently upgraded flutter so some packages require http versions more the 0.12.2 so I had to update but global configurations need 0.12.2 which is why i had to take out global configurations and look in to other packeges please look into it

**Comment by rahat1994** [comment]
`[flutter_application] flutter pub get

--

Running "flutter pub get" in flutter_application...             
Because markets depends on global_configuration 1.6.0 which depends on http ^0.12.2, http ^0.12.2 is required.

So, because markets depends on http ^0.13.0, version solving failed.
pub get failed (1; So, because markets depends on http ^0.13.0, version solving failed.)
exit code 1
[flutter_application] flutter pub get
Running "flutter pub get" in flutter_application...             
Because markets depends on global_configuration 1.6.0 which depends on http ^0.12.2, http ^0.12.2 is required.

So, because markets depends on http ^0.13.0, version solving failed.
pub get failed (1; So, because markets depends on http ^0.13.0, version solving failed.)
exit code 1`

**Comment by Ephenodrom** [comment]
Hello @rahat1994 

I will update the package next week. I will inform you when the update is ready.

**Comment by Ephenodrom** [comment]
@rahat1994 
Please update to version "2.0.0-nullsafety.1".
