### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by dragouf** [Ephenodrom/Flutter-Global-Config#35]
just a simple question. Why null safety is still not released. Is there any bug with it ?

**Comment by smelcher** [comment]
Same question.  Is this plugin still be developed?  If not, can come someone suggest an alternative?

**Comment by diegoalex** [comment]
If you're on the Flutter 3.7 you should use the --dart-define-from-file , which is safer and no need of a third party library.

There's an explanation here:
https://itnext.io/flutter-3-7-and-a-new-way-of-defining-compile-time-variables-f63db8a4f6e2

**Comment by Ephenodrom** [comment]
Version 2.0.0 is out now.
