### ISSUE TITLE
Please allow the use of a different folder

### ISSUE THREAD

**Issue by Pikaju** [Ephenodrom/Flutter-Global-Config#5]
"cfg" does not work with some naming conventions, and perhaps some people don't even use a folder called "assets".

**Comment by Ephenodrom** [comment]
I will work on this on the weekend. Stay tuned for an update.

**Comment by Ephenodrom** [comment]
@Pikaju 
Please update to version 1.0.0 and try the following :

```dart
GlobalConfiguration().loadFromPath("/path/file.json");
```

Please give me a feedback if it works for you as intended.

Regards

**Comment by Ephenodrom** [comment]
Function added with version 1.0.0
