### ISSUE TITLE
setValue key.runtimeType != appConfig[key].runtimeType

### ISSUE THREAD

**Issue by git-gz** [Ephenodrom/Flutter-Global-Config#6]
`  /// Write a value from persistent storage, throwing an exception if it's not
  /// the correct type
  void setValue(key, value) {
key.runtimeType != appConfig[key].runtimeType
          ? throw("wrong type")
          : appConfig.update(key, value);
  }`
The runtimeType of the key and value must be ==? 
why?

**Comment by Ephenodrom** [comment]
@git-gz 
Hello,
I fixed the bug and improved the usage of the setValue method. Update to version 1.1.0!

BEFORE:

```dart
 cfg().setValue("key1", (string)  => "value2");
```
NOW :

```dart
 cfg().setValue("key1", "value2");
```
