### ISSUE TITLE
Support the memory configurations

### ISSUE THREAD

**Issue by ductranit** [Ephenodrom/Flutter-Global-Config#7]
Sometime we need to store memory configurations (not in persistent storage), it would be great if this package supports to this.
I'd expect something like:
```
void addMemoryValue(String key, dynamic value){}
```
And it just uses the same for `getString()`, `getDouble()`... (memory cache first)
And all the memory configurations should be cleared when exit app.
Thanks!

**Comment by Ephenodrom** [comment]
@ductranit thanks for the feature request. I will take a look into it. I will give a feedback in a few days.

**Comment by Ephenodrom** [comment]
Hello @ductranit 

So for me to understand, you would like to store some variables in a different cache and grab the value for the key from the "memory" cache if the key exists in the "memory" cache, if not, grab the value for the key from the normal cache ?

Another idea how to get this behavior is using the following method : 
```dart
 void addValue(String key, dynamic value) =>
      appConfig.putIfAbsent(key, () => value);
```
This will add any value to the storage at a certain key. This is not persistent ( I updated the code doc ). Upon next restart of the app the key and value are not there anymore.


Regards

**Comment by ductranit** [comment]
@Ephenodrom great, it makes sense. Just have a look at the code & I can see it just stores variables on memory map like you said. The `persistent` in the doc was confusing me before.
Thanks for your support!

**Comment by Ephenodrom** [comment]
@ductranit 
Yeah i also found it a bit confusing so i updated the code documentation. 

Thank you for using this package :).

Regards
