### ISSUE TITLE
Resets Configuration on Restarting Application

### ISSUE THREAD

**Issue by Zeyad-A-Ramadan** [Ephenodrom/Flutter-Global-Config#8]
For example, I'm using a string named language, its initial value is 'en'. when i change it to for example 'ar', then close the application and reopen it, the value is set back to 'en'. Is it my issue only? Am i using it wrongly or something like that?

**Comment by Ephenodrom** [comment]
Hello @Zeyad-A-Ramadan 
The global config package is not persistent. You once load the configuration from a source and the only purpose of the package is to give access to it everywhere inside your flutter app.

If you want to update data and it has to be persistent check out my EZ Flutter Framework at https://github.com/Ephenodrom/EZ-Flutter. The EZ Flutter framework uses the global config package to store data persistent. Check out the documentation at https://ez-flutter.de/docs/application_settings.

If you don't want to use the framework, take a look at https://github.com/Ephenodrom/EZ-Flutter/blob/master/lib/src/model/EzSettings.dart and create your own implementation.

I hope that makes it clear :).

Regards and thanks for opening an issue!

**Comment by Zeyad-A-Ramadan** [comment]
Thank you for your response and for clarifying it for me. I'll see what i
can do. Thank you once again for your help.
